export const surgeryNames = [
	'Aneurisma Cerebral',
	'Artrodese de coluna cervical',
	'Artrodese de coluna Lombo - sacra',
	'Artrodese coluna torácica',
	'Biópsia Estereotácica',
	'Bloqueio da coluna',
	'Bloqueio Ocipital',
	'Cranioplastia',
	'Canal estreito Lombar',
	'Carótida',
	'DBS',
	'DVP',
	'Desbridamento de FO',
	'Descompressão de Nervo Periférico',
	'DLP',
	'Escoliose',
	'Estapedectomia',
	'Extensos ferimentos',
	'Hérnia de disco Cervical',
	'Fogarty',
	'Janetta',
	'Hematoma Subdural Crônico',
	'Hérnia de disco Lombar',
	'HDL endoscópica',
	'Hérnia de disco torácica',
	'Laminoplastia cervical',
	'Laringectomia',
	'MAV',
	'MIcro Decorticação',
	'Micro de Laringe',
	'Paralisia Pregas Vocais',
	'Plexo braquial',
	'Punção Lombar',
	'Reconstrução Craniana',
	'Rinoplastia',
	'Septoplastia',
	'Terceiro ventriculostomia Endoscópica',
	'Tumor Cerebral',
	'Tumor de Coluna',
	'Tumor de Hipófise',
	'Tumor Medular',
	'Tumor de Nervo Periférico',
	'Túnel do Carpo',
	'Troca de gerador de DBS',
	'Timpanotomia',
	'Traqueostomia',
	'Vertebroplastia'
];
export const surgeonNames = [
	'Albert Brasil',
	'Alexandre Reis',
	'Alisson Teles',
	'Antonio Vial',
	'Bruno',
	'Cirurgia Torácica',
	'Craniofacial',
	'Jorge Kraemer',
	'Marcelo Ferreira',
	'Maria de Lourdes Villar Zeltzer',
	'Otorrino',
	'Paulo Worm',
	'Pedro Gobbato',
	'Roberto José Farias',
	'Rogerio Novaes',
	'Schuster',
	'Tielen Sigalles',
	'Tobias Ludwig'
];
export enum CurrentStep {
	Criacao = 'Criação',
	DocsEnviadosHJS = 'Enviar documentos para a secretária do HSJ',
	SolicitadoOPME = 'Solicitar orçamento OPME',
	RetornoOPME = 'Retorno do orçamento do OPME',
	DocsEnviadosConvenio = 'Encaminhar documentos para convênio',
	RespostaConvenio = 'Resposta do convênio',
	EnvioJustificativas = 'Envio de Justificativas/documentos',
	RespostaJustificativas = 'Resposta após justificativa',
	Concluido = 'Concluído'
}
export const steps = [
	CurrentStep.Criacao,
	CurrentStep.DocsEnviadosHJS,
	CurrentStep.SolicitadoOPME,
	CurrentStep.RetornoOPME,
	CurrentStep.DocsEnviadosConvenio,
	CurrentStep.RespostaConvenio,
	CurrentStep.EnvioJustificativas,
	CurrentStep.RespostaJustificativas,
	CurrentStep.Concluido
];
export enum ResponseStatus {
	Autorizada = 'Autorizada',
	Pendente = 'Pendente de justificativas / documentos',
	NovasJustificativas = 'Necessita novas justificativas'
}
